// Copyright <holder> All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: cloudland/v1/cloudland.proto

package cloudlandpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          // 消息 ID（通常 100）
	Extra         int32                  `protobuf:"varint,2,opt,name=extra,proto3" json:"extra,omitempty"`    // 附加参数（节点 ID 或优先级）
	Control       string                 `protobuf:"bytes,3,opt,name=control,proto3" json:"control,omitempty"` // 路由指令，如 "inter=5", "select=zone0:1,2 cpu=4"
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"` // Shell 命令
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExecuteRequest) GetExtra() int32 {
	if x != nil {
		return x.Extra
	}
	return 0
}

func (x *ExecuteRequest) GetControl() string {
	if x != nil {
		return x.Control
	}
	return ""
}

func (x *ExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ExecuteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteReply) Reset() {
	*x = ExecuteReply{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteReply) ProtoMessage() {}

func (x *ExecuteReply) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteReply.ProtoReflect.Descriptor instead.
func (*ExecuteReply) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NodeAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAddRequest) Reset() {
	*x = NodeAddRequest{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAddRequest) ProtoMessage() {}

func (x *NodeAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAddRequest.ProtoReflect.Descriptor instead.
func (*NodeAddRequest) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{2}
}

func (x *NodeAddRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeAddRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeAddRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type NodeAddReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAddReply) Reset() {
	*x = NodeAddReply{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAddReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAddReply) ProtoMessage() {}

func (x *NodeAddReply) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAddReply.ProtoReflect.Descriptor instead.
func (*NodeAddReply) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{3}
}

func (x *NodeAddReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeAddReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeAddReply) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *NodeAddReply) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type NodeRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRemoveRequest) Reset() {
	*x = NodeRemoveRequest{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRemoveRequest) ProtoMessage() {}

func (x *NodeRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRemoveRequest.ProtoReflect.Descriptor instead.
func (*NodeRemoveRequest) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{4}
}

func (x *NodeRemoveRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NodeRemoveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRemoveReply) Reset() {
	*x = NodeRemoveReply{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRemoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRemoveReply) ProtoMessage() {}

func (x *NodeRemoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRemoveReply.ProtoReflect.Descriptor instead.
func (*NodeRemoveReply) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{5}
}

func (x *NodeRemoveReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Control       string                 `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	Filepath      string                 `protobuf:"bytes,3,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Filesize      int64                  `protobuf:"varint,4,opt,name=filesize,proto3" json:"filesize,omitempty"`
	Checksum      int32                  `protobuf:"varint,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Fileseek      int64                  `protobuf:"varint,6,opt,name=fileseek,proto3" json:"fileseek,omitempty"`
	Content       []byte                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Extra         int32                  `protobuf:"varint,8,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{6}
}

func (x *FileChunk) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileChunk) GetControl() string {
	if x != nil {
		return x.Control
	}
	return ""
}

func (x *FileChunk) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *FileChunk) GetFilesize() int64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *FileChunk) GetChecksum() int32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *FileChunk) GetFileseek() int64 {
	if x != nil {
		return x.Fileseek
	}
	return 0
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileChunk) GetExtra() int32 {
	if x != nil {
		return x.Extra
	}
	return 0
}

type TransmitAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransmitAck) Reset() {
	*x = TransmitAck{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransmitAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransmitAck) ProtoMessage() {}

func (x *TransmitAck) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransmitAck.ProtoReflect.Descriptor instead.
func (*TransmitAck) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{7}
}

func (x *TransmitAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{8}
}

type ListGroupsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []string               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsReply) Reset() {
	*x = ListGroupsReply{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsReply) ProtoMessage() {}

func (x *ListGroupsReply) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsReply.ProtoReflect.Descriptor instead.
func (*ListGroupsReply) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{9}
}

func (x *ListGroupsReply) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

// === cloudlet → cland 上行消息 ===
type CloudletMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CloudletMessage_Register
	//	*CloudletMessage_Result
	//	*CloudletMessage_Callback
	//	*CloudletMessage_Error
	Payload       isCloudletMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudletMessage) Reset() {
	*x = CloudletMessage{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudletMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudletMessage) ProtoMessage() {}

func (x *CloudletMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudletMessage.ProtoReflect.Descriptor instead.
func (*CloudletMessage) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{10}
}

func (x *CloudletMessage) GetPayload() isCloudletMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CloudletMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*CloudletMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *CloudletMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*CloudletMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *CloudletMessage) GetCallback() *CallbackLine {
	if x != nil {
		if x, ok := x.Payload.(*CloudletMessage_Callback); ok {
			return x.Callback
		}
	}
	return nil
}

func (x *CloudletMessage) GetError() *ErrorReport {
	if x != nil {
		if x, ok := x.Payload.(*CloudletMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCloudletMessage_Payload interface {
	isCloudletMessage_Payload()
}

type CloudletMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type CloudletMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type CloudletMessage_Callback struct {
	Callback *CallbackLine `protobuf:"bytes,3,opt,name=callback,proto3,oneof"`
}

type CloudletMessage_Error struct {
	Error *ErrorReport `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*CloudletMessage_Register) isCloudletMessage_Payload() {}

func (*CloudletMessage_Result) isCloudletMessage_Payload() {}

func (*CloudletMessage_Callback) isCloudletMessage_Payload() {}

func (*CloudletMessage_Error) isCloudletMessage_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // NODE_ID
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int32                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Control       string                 `protobuf:"bytes,3,opt,name=control,proto3" json:"control,omitempty"`                                                                                                         // "callback"
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`                                                                                                           // stdout 单行
	TraceContext  map[string]string      `protobuf:"bytes,6,rep,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // W3C trace 上下文（traceparent/tracestate）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{12}
}

func (x *CommandResult) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *CommandResult) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *CommandResult) GetControl() string {
	if x != nil {
		return x.Control
	}
	return ""
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResult) GetTraceContext() map[string]string {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

type CallbackLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int32                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`                                                                                                         // 从 |:-COMMAND-:| 解析出的命令
	TraceContext  map[string]string      `protobuf:"bytes,5,rep,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // W3C trace 上下文
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackLine) Reset() {
	*x = CallbackLine{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackLine) ProtoMessage() {}

func (x *CallbackLine) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackLine.ProtoReflect.Descriptor instead.
func (*CallbackLine) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{13}
}

func (x *CallbackLine) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *CallbackLine) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *CallbackLine) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CallbackLine) GetTraceContext() map[string]string {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

type ErrorReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int32                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	TraceContext  map[string]string      `protobuf:"bytes,6,rep,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // W3C trace 上下文
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorReport) Reset() {
	*x = ErrorReport{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReport) ProtoMessage() {}

func (x *ErrorReport) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReport.ProtoReflect.Descriptor instead.
func (*ErrorReport) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{14}
}

func (x *ErrorReport) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ErrorReport) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ErrorReport) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ErrorReport) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ErrorReport) GetTraceContext() map[string]string {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

// === cland → cloudlet 下行消息 ===
type ClandMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClandMessage_RegisterAck
	//	*ClandMessage_Command
	//	*ClandMessage_File
	//	*ClandMessage_Shutdown
	Payload       isClandMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClandMessage) Reset() {
	*x = ClandMessage{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClandMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClandMessage) ProtoMessage() {}

func (x *ClandMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClandMessage.ProtoReflect.Descriptor instead.
func (*ClandMessage) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{15}
}

func (x *ClandMessage) GetPayload() isClandMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClandMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ClandMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ClandMessage) GetCommand() *CommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClandMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ClandMessage) GetFile() *FileTransfer {
	if x != nil {
		if x, ok := x.Payload.(*ClandMessage_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *ClandMessage) GetShutdown() *ShutdownRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClandMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isClandMessage_Payload interface {
	isClandMessage_Payload()
}

type ClandMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ClandMessage_Command struct {
	Command *CommandRequest `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type ClandMessage_File struct {
	File *FileTransfer `protobuf:"bytes,3,opt,name=file,proto3,oneof"`
}

type ClandMessage_Shutdown struct {
	Shutdown *ShutdownRequest `protobuf:"bytes,4,opt,name=shutdown,proto3,oneof"`
}

func (*ClandMessage_RegisterAck) isClandMessage_Payload() {}

func (*ClandMessage_Command) isClandMessage_Payload() {}

func (*ClandMessage_File) isClandMessage_Payload() {}

func (*ClandMessage_Shutdown) isClandMessage_Payload() {}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{16}
}

func (x *ShutdownRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int32                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Extra         int32                  `protobuf:"varint,2,opt,name=extra,proto3" json:"extra,omitempty"`
	Control       string                 `protobuf:"bytes,3,opt,name=control,proto3" json:"control,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	TraceContext  map[string]string      `protobuf:"bytes,6,rep,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // W3C trace 上下文，cloudlet 据此创建子 span
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{18}
}

func (x *CommandRequest) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *CommandRequest) GetExtra() int32 {
	if x != nil {
		return x.Extra
	}
	return 0
}

func (x *CommandRequest) GetControl() string {
	if x != nil {
		return x.Control
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetTraceContext() map[string]string {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

type FileTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int32                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Filepath      string                 `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Filesize      int64                  `protobuf:"varint,3,opt,name=filesize,proto3" json:"filesize,omitempty"`
	Fileseek      int64                  `protobuf:"varint,4,opt,name=fileseek,proto3" json:"fileseek,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Checksum      int32                  `protobuf:"varint,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	TraceContext  map[string]string      `protobuf:"bytes,7,rep,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // W3C trace 上下文，cloudlet 据此创建子 span
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransfer) Reset() {
	*x = FileTransfer{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransfer) ProtoMessage() {}

func (x *FileTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransfer.ProtoReflect.Descriptor instead.
func (*FileTransfer) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{19}
}

func (x *FileTransfer) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *FileTransfer) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *FileTransfer) GetFilesize() int64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *FileTransfer) GetFileseek() int64 {
	if x != nil {
		return x.Fileseek
	}
	return 0
}

func (x *FileTransfer) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileTransfer) GetChecksum() int32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *FileTransfer) GetTraceContext() map[string]string {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

type HealthReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname         string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CpuAvailable     int64                  `protobuf:"varint,3,opt,name=cpu_available,json=cpuAvailable,proto3" json:"cpu_available,omitempty"`
	CpuTotal         int64                  `protobuf:"varint,4,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	MemoryAvailable  int64                  `protobuf:"varint,5,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	MemoryTotal      int64                  `protobuf:"varint,6,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	DiskAvailable    int64                  `protobuf:"varint,7,opt,name=disk_available,json=diskAvailable,proto3" json:"disk_available,omitempty"`
	DiskTotal        int64                  `protobuf:"varint,8,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	NetworkAvailable int64                  `protobuf:"varint,9,opt,name=network_available,json=networkAvailable,proto3" json:"network_available,omitempty"`
	NetworkTotal     int64                  `protobuf:"varint,10,opt,name=network_total,json=networkTotal,proto3" json:"network_total,omitempty"`
	LoadAvailable    int64                  `protobuf:"varint,11,opt,name=load_available,json=loadAvailable,proto3" json:"load_available,omitempty"`
	LoadTotal        int64                  `protobuf:"varint,12,opt,name=load_total,json=loadTotal,proto3" json:"load_total,omitempty"`
	RawReport        string                 `protobuf:"bytes,13,opt,name=raw_report,json=rawReport,proto3" json:"raw_report,omitempty"`             // report_rc.sh 第一行原始输出
	CallbackLines    []string               `protobuf:"bytes,14,rep,name=callback_lines,json=callbackLines,proto3" json:"callback_lines,omitempty"` // 后续行
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{20}
}

func (x *HealthReport) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *HealthReport) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HealthReport) GetCpuAvailable() int64 {
	if x != nil {
		return x.CpuAvailable
	}
	return 0
}

func (x *HealthReport) GetCpuTotal() int64 {
	if x != nil {
		return x.CpuTotal
	}
	return 0
}

func (x *HealthReport) GetMemoryAvailable() int64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *HealthReport) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *HealthReport) GetDiskAvailable() int64 {
	if x != nil {
		return x.DiskAvailable
	}
	return 0
}

func (x *HealthReport) GetDiskTotal() int64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *HealthReport) GetNetworkAvailable() int64 {
	if x != nil {
		return x.NetworkAvailable
	}
	return 0
}

func (x *HealthReport) GetNetworkTotal() int64 {
	if x != nil {
		return x.NetworkTotal
	}
	return 0
}

func (x *HealthReport) GetLoadAvailable() int64 {
	if x != nil {
		return x.LoadAvailable
	}
	return 0
}

func (x *HealthReport) GetLoadTotal() int64 {
	if x != nil {
		return x.LoadTotal
	}
	return 0
}

func (x *HealthReport) GetRawReport() string {
	if x != nil {
		return x.RawReport
	}
	return ""
}

func (x *HealthReport) GetCallbackLines() []string {
	if x != nil {
		return x.CallbackLines
	}
	return nil
}

type HealthReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReportAck) Reset() {
	*x = HealthReportAck{}
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReportAck) ProtoMessage() {}

func (x *HealthReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_cloudland_v1_cloudland_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReportAck.ProtoReflect.Descriptor instead.
func (*HealthReportAck) Descriptor() ([]byte, []int) {
	return file_cloudland_v1_cloudland_proto_rawDescGZIP(), []int{21}
}

func (x *HealthReportAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_cloudland_v1_cloudland_proto protoreflect.FileDescriptor

const file_cloudland_v1_cloudland_proto_rawDesc = "" +
	"\n" +
	"\x1ccloudland/v1/cloudland.proto\x12\fcloudland.v1\"z\n" +
	"\x0eExecuteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05extra\x18\x02 \x01(\x05R\x05extra\x12\x18\n" +
	"\acontrol\x18\x03 \x01(\tR\acontrol\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommandJ\x04\b\x05\x10\x06R\btrace_id\"&\n" +
	"\fExecuteReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"R\n" +
	"\x0eNodeAddRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\"v\n" +
	"\fNodeAddReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x04 \x01(\tR\n" +
	"privateKey\"#\n" +
	"\x11NodeRemoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\")\n" +
	"\x0fNodeRemoveReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xd5\x01\n" +
	"\tFileChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\acontrol\x18\x02 \x01(\tR\acontrol\x12\x1a\n" +
	"\bfilepath\x18\x03 \x01(\tR\bfilepath\x12\x1a\n" +
	"\bfilesize\x18\x04 \x01(\x03R\bfilesize\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\x05R\bchecksum\x12\x1a\n" +
	"\bfileseek\x18\x06 \x01(\x03R\bfileseek\x12\x18\n" +
	"\acontent\x18\a \x01(\fR\acontent\x12\x14\n" +
	"\x05extra\x18\b \x01(\x05R\x05extra\"%\n" +
	"\vTransmitAck\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x13\n" +
	"\x11ListGroupsRequest\")\n" +
	"\x0fListGroupsReply\x12\x16\n" +
	"\x06groups\x18\x01 \x03(\tR\x06groups\"\xfd\x01\n" +
	"\x0fCloudletMessage\x12;\n" +
	"\bregister\x18\x01 \x01(\v2\x1d.cloudland.v1.RegisterRequestH\x00R\bregister\x125\n" +
	"\x06result\x18\x02 \x01(\v2\x1b.cloudland.v1.CommandResultH\x00R\x06result\x128\n" +
	"\bcallback\x18\x03 \x01(\v2\x1a.cloudland.v1.CallbackLineH\x00R\bcallback\x121\n" +
	"\x05error\x18\x04 \x01(\v2\x19.cloudland.v1.ErrorReportH\x00R\x05errorB\t\n" +
	"\apayload\"F\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"\x96\x02\n" +
	"\rCommandResult\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x05R\x05msgId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\acontrol\x18\x03 \x01(\tR\acontrol\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12R\n" +
	"\rtrace_context\x18\x06 \x03(\v2-.cloudland.v1.CommandResult.TraceContextEntryR\ftraceContext\x1a?\n" +
	"\x11TraceContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x05\x10\x06R\btrace_id\"\xfc\x01\n" +
	"\fCallbackLine\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x05R\x05msgId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12Q\n" +
	"\rtrace_context\x18\x05 \x03(\v2,.cloudland.v1.CallbackLine.TraceContextEntryR\ftraceContext\x1a?\n" +
	"\x11TraceContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x04\x10\x05R\btrace_id\"\x97\x02\n" +
	"\vErrorReport\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x05R\x05msgId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12P\n" +
	"\rtrace_context\x18\x06 \x03(\v2+.cloudland.v1.ErrorReport.TraceContextEntryR\ftraceContext\x1a?\n" +
	"\x11TraceContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x05\x10\x06R\btrace_id\"\x82\x02\n" +
	"\fClandMessage\x12>\n" +
	"\fregister_ack\x18\x01 \x01(\v2\x19.cloudland.v1.RegisterAckH\x00R\vregisterAck\x128\n" +
	"\acommand\x18\x02 \x01(\v2\x1c.cloudland.v1.CommandRequestH\x00R\acommand\x120\n" +
	"\x04file\x18\x03 \x01(\v2\x1a.cloudland.v1.FileTransferH\x00R\x04file\x12;\n" +
	"\bshutdown\x18\x04 \x01(\v2\x1d.cloudland.v1.ShutdownRequestH\x00R\bshutdownB\t\n" +
	"\apayload\")\n" +
	"\x0fShutdownRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"=\n" +
	"\vRegisterAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x97\x02\n" +
	"\x0eCommandRequest\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x05R\x05msgId\x12\x14\n" +
	"\x05extra\x18\x02 \x01(\x05R\x05extra\x12\x18\n" +
	"\acontrol\x18\x03 \x01(\tR\acontrol\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12S\n" +
	"\rtrace_context\x18\x06 \x03(\v2..cloudland.v1.CommandRequest.TraceContextEntryR\ftraceContext\x1a?\n" +
	"\x11TraceContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x05\x10\x06R\btrace_id\"\xc3\x02\n" +
	"\fFileTransfer\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x05R\x05msgId\x12\x1a\n" +
	"\bfilepath\x18\x02 \x01(\tR\bfilepath\x12\x1a\n" +
	"\bfilesize\x18\x03 \x01(\x03R\bfilesize\x12\x1a\n" +
	"\bfileseek\x18\x04 \x01(\x03R\bfileseek\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\x05R\bchecksum\x12Q\n" +
	"\rtrace_context\x18\a \x03(\v2,.cloudland.v1.FileTransfer.TraceContextEntryR\ftraceContext\x1a?\n" +
	"\x11TraceContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x03\n" +
	"\fHealthReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12#\n" +
	"\rcpu_available\x18\x03 \x01(\x03R\fcpuAvailable\x12\x1b\n" +
	"\tcpu_total\x18\x04 \x01(\x03R\bcpuTotal\x12)\n" +
	"\x10memory_available\x18\x05 \x01(\x03R\x0fmemoryAvailable\x12!\n" +
	"\fmemory_total\x18\x06 \x01(\x03R\vmemoryTotal\x12%\n" +
	"\x0edisk_available\x18\a \x01(\x03R\rdiskAvailable\x12\x1d\n" +
	"\n" +
	"disk_total\x18\b \x01(\x03R\tdiskTotal\x12+\n" +
	"\x11network_available\x18\t \x01(\x03R\x10networkAvailable\x12#\n" +
	"\rnetwork_total\x18\n" +
	" \x01(\x03R\fnetworkTotal\x12%\n" +
	"\x0eload_available\x18\v \x01(\x03R\rloadAvailable\x12\x1d\n" +
	"\n" +
	"load_total\x18\f \x01(\x03R\tloadTotal\x12\x1d\n" +
	"\n" +
	"raw_report\x18\r \x01(\tR\trawReport\x12%\n" +
	"\x0ecallback_lines\x18\x0e \x03(\tR\rcallbackLines\"-\n" +
	"\x0fHealthReportAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\xfa\x02\n" +
	"\fClandService\x12C\n" +
	"\aExecute\x12\x1c.cloudland.v1.ExecuteRequest\x1a\x1a.cloudland.v1.ExecuteReply\x12C\n" +
	"\aNodeAdd\x12\x1c.cloudland.v1.NodeAddRequest\x1a\x1a.cloudland.v1.NodeAddReply\x12L\n" +
	"\n" +
	"NodeRemove\x12\x1f.cloudland.v1.NodeRemoveRequest\x1a\x1d.cloudland.v1.NodeRemoveReply\x12D\n" +
	"\fTransmitFile\x12\x17.cloudland.v1.FileChunk\x1a\x19.cloudland.v1.TransmitAck(\x01\x12L\n" +
	"\n" +
	"ListGroups\x12\x1f.cloudland.v1.ListGroupsRequest\x1a\x1d.cloudland.v1.ListGroupsReply2\xac\x01\n" +
	"\x0fCloudletService\x12N\n" +
	"\rCommandStream\x12\x1d.cloudland.v1.CloudletMessage\x1a\x1a.cloudland.v1.ClandMessage(\x010\x01\x12I\n" +
	"\fReportHealth\x12\x1a.cloudland.v1.HealthReport\x1a\x1d.cloudland.v1.HealthReportAckB'Z%api/src/proto/cloudlandpb;cloudlandpbb\x06proto3"

var (
	file_cloudland_v1_cloudland_proto_rawDescOnce sync.Once
	file_cloudland_v1_cloudland_proto_rawDescData []byte
)

func file_cloudland_v1_cloudland_proto_rawDescGZIP() []byte {
	file_cloudland_v1_cloudland_proto_rawDescOnce.Do(func() {
		file_cloudland_v1_cloudland_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloudland_v1_cloudland_proto_rawDesc), len(file_cloudland_v1_cloudland_proto_rawDesc)))
	})
	return file_cloudland_v1_cloudland_proto_rawDescData
}

var file_cloudland_v1_cloudland_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_cloudland_v1_cloudland_proto_goTypes = []any{
	(*ExecuteRequest)(nil),    // 0: cloudland.v1.ExecuteRequest
	(*ExecuteReply)(nil),      // 1: cloudland.v1.ExecuteReply
	(*NodeAddRequest)(nil),    // 2: cloudland.v1.NodeAddRequest
	(*NodeAddReply)(nil),      // 3: cloudland.v1.NodeAddReply
	(*NodeRemoveRequest)(nil), // 4: cloudland.v1.NodeRemoveRequest
	(*NodeRemoveReply)(nil),   // 5: cloudland.v1.NodeRemoveReply
	(*FileChunk)(nil),         // 6: cloudland.v1.FileChunk
	(*TransmitAck)(nil),       // 7: cloudland.v1.TransmitAck
	(*ListGroupsRequest)(nil), // 8: cloudland.v1.ListGroupsRequest
	(*ListGroupsReply)(nil),   // 9: cloudland.v1.ListGroupsReply
	(*CloudletMessage)(nil),   // 10: cloudland.v1.CloudletMessage
	(*RegisterRequest)(nil),   // 11: cloudland.v1.RegisterRequest
	(*CommandResult)(nil),     // 12: cloudland.v1.CommandResult
	(*CallbackLine)(nil),      // 13: cloudland.v1.CallbackLine
	(*ErrorReport)(nil),       // 14: cloudland.v1.ErrorReport
	(*ClandMessage)(nil),      // 15: cloudland.v1.ClandMessage
	(*ShutdownRequest)(nil),   // 16: cloudland.v1.ShutdownRequest
	(*RegisterAck)(nil),       // 17: cloudland.v1.RegisterAck
	(*CommandRequest)(nil),    // 18: cloudland.v1.CommandRequest
	(*FileTransfer)(nil),      // 19: cloudland.v1.FileTransfer
	(*HealthReport)(nil),      // 20: cloudland.v1.HealthReport
	(*HealthReportAck)(nil),   // 21: cloudland.v1.HealthReportAck
	nil,                       // 22: cloudland.v1.CommandResult.TraceContextEntry
	nil,                       // 23: cloudland.v1.CallbackLine.TraceContextEntry
	nil,                       // 24: cloudland.v1.ErrorReport.TraceContextEntry
	nil,                       // 25: cloudland.v1.CommandRequest.TraceContextEntry
	nil,                       // 26: cloudland.v1.FileTransfer.TraceContextEntry
}
var file_cloudland_v1_cloudland_proto_depIdxs = []int32{
	11, // 0: cloudland.v1.CloudletMessage.register:type_name -> cloudland.v1.RegisterRequest
	12, // 1: cloudland.v1.CloudletMessage.result:type_name -> cloudland.v1.CommandResult
	13, // 2: cloudland.v1.CloudletMessage.callback:type_name -> cloudland.v1.CallbackLine
	14, // 3: cloudland.v1.CloudletMessage.error:type_name -> cloudland.v1.ErrorReport
	22, // 4: cloudland.v1.CommandResult.trace_context:type_name -> cloudland.v1.CommandResult.TraceContextEntry
	23, // 5: cloudland.v1.CallbackLine.trace_context:type_name -> cloudland.v1.CallbackLine.TraceContextEntry
	24, // 6: cloudland.v1.ErrorReport.trace_context:type_name -> cloudland.v1.ErrorReport.TraceContextEntry
	17, // 7: cloudland.v1.ClandMessage.register_ack:type_name -> cloudland.v1.RegisterAck
	18, // 8: cloudland.v1.ClandMessage.command:type_name -> cloudland.v1.CommandRequest
	19, // 9: cloudland.v1.ClandMessage.file:type_name -> cloudland.v1.FileTransfer
	16, // 10: cloudland.v1.ClandMessage.shutdown:type_name -> cloudland.v1.ShutdownRequest
	25, // 11: cloudland.v1.CommandRequest.trace_context:type_name -> cloudland.v1.CommandRequest.TraceContextEntry
	26, // 12: cloudland.v1.FileTransfer.trace_context:type_name -> cloudland.v1.FileTransfer.TraceContextEntry
	0,  // 13: cloudland.v1.ClandService.Execute:input_type -> cloudland.v1.ExecuteRequest
	2,  // 14: cloudland.v1.ClandService.NodeAdd:input_type -> cloudland.v1.NodeAddRequest
	4,  // 15: cloudland.v1.ClandService.NodeRemove:input_type -> cloudland.v1.NodeRemoveRequest
	6,  // 16: cloudland.v1.ClandService.TransmitFile:input_type -> cloudland.v1.FileChunk
	8,  // 17: cloudland.v1.ClandService.ListGroups:input_type -> cloudland.v1.ListGroupsRequest
	10, // 18: cloudland.v1.CloudletService.CommandStream:input_type -> cloudland.v1.CloudletMessage
	20, // 19: cloudland.v1.CloudletService.ReportHealth:input_type -> cloudland.v1.HealthReport
	1,  // 20: cloudland.v1.ClandService.Execute:output_type -> cloudland.v1.ExecuteReply
	3,  // 21: cloudland.v1.ClandService.NodeAdd:output_type -> cloudland.v1.NodeAddReply
	5,  // 22: cloudland.v1.ClandService.NodeRemove:output_type -> cloudland.v1.NodeRemoveReply
	7,  // 23: cloudland.v1.ClandService.TransmitFile:output_type -> cloudland.v1.TransmitAck
	9,  // 24: cloudland.v1.ClandService.ListGroups:output_type -> cloudland.v1.ListGroupsReply
	15, // 25: cloudland.v1.CloudletService.CommandStream:output_type -> cloudland.v1.ClandMessage
	21, // 26: cloudland.v1.CloudletService.ReportHealth:output_type -> cloudland.v1.HealthReportAck
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cloudland_v1_cloudland_proto_init() }
func file_cloudland_v1_cloudland_proto_init() {
	if File_cloudland_v1_cloudland_proto != nil {
		return
	}
	file_cloudland_v1_cloudland_proto_msgTypes[10].OneofWrappers = []any{
		(*CloudletMessage_Register)(nil),
		(*CloudletMessage_Result)(nil),
		(*CloudletMessage_Callback)(nil),
		(*CloudletMessage_Error)(nil),
	}
	file_cloudland_v1_cloudland_proto_msgTypes[15].OneofWrappers = []any{
		(*ClandMessage_RegisterAck)(nil),
		(*ClandMessage_Command)(nil),
		(*ClandMessage_File)(nil),
		(*ClandMessage_Shutdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloudland_v1_cloudland_proto_rawDesc), len(file_cloudland_v1_cloudland_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cloudland_v1_cloudland_proto_goTypes,
		DependencyIndexes: file_cloudland_v1_cloudland_proto_depIdxs,
		MessageInfos:      file_cloudland_v1_cloudland_proto_msgTypes,
	}.Build()
	File_cloudland_v1_cloudland_proto = out.File
	file_cloudland_v1_cloudland_proto_goTypes = nil
	file_cloudland_v1_cloudland_proto_depIdxs = nil
}
