// Copyright <holder> All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: cloudland/v1/cloudland.proto

package cloudlandpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClandService_Execute_FullMethodName      = "/cloudland.v1.ClandService/Execute"
	ClandService_NodeAdd_FullMethodName      = "/cloudland.v1.ClandService/NodeAdd"
	ClandService_NodeRemove_FullMethodName   = "/cloudland.v1.ClandService/NodeRemove"
	ClandService_TransmitFile_FullMethodName = "/cloudland.v1.ClandService/TransmitFile"
	ClandService_ListGroups_FullMethodName   = "/cloudland.v1.ClandService/ListGroups"
)

// ClandServiceClient is the client API for ClandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ====================================================================
// ClandService: clapi → cland（控制面内部通信）
// 替代当前 cland 的 3 个 HTTP 端点
// ====================================================================
type ClandServiceClient interface {
	// 替代 POST /internal/execute
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteReply, error)
	// 替代 POST /internal/node/add
	NodeAdd(ctx context.Context, in *NodeAddRequest, opts ...grpc.CallOption) (*NodeAddReply, error)
	// 替代 POST /internal/node/remove
	NodeRemove(ctx context.Context, in *NodeRemoveRequest, opts ...grpc.CallOption) (*NodeRemoveReply, error)
	// 文件传输（控制面 → 计算节点）
	TransmitFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, TransmitAck], error)
	// 分组管理
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsReply, error)
}

type clandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClandServiceClient(cc grpc.ClientConnInterface) ClandServiceClient {
	return &clandServiceClient{cc}
}

func (c *clandServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteReply)
	err := c.cc.Invoke(ctx, ClandService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clandServiceClient) NodeAdd(ctx context.Context, in *NodeAddRequest, opts ...grpc.CallOption) (*NodeAddReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeAddReply)
	err := c.cc.Invoke(ctx, ClandService_NodeAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clandServiceClient) NodeRemove(ctx context.Context, in *NodeRemoveRequest, opts ...grpc.CallOption) (*NodeRemoveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRemoveReply)
	err := c.cc.Invoke(ctx, ClandService_NodeRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clandServiceClient) TransmitFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, TransmitAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClandService_ServiceDesc.Streams[0], ClandService_TransmitFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, TransmitAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClandService_TransmitFileClient = grpc.ClientStreamingClient[FileChunk, TransmitAck]

func (c *clandServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsReply)
	err := c.cc.Invoke(ctx, ClandService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClandServiceServer is the server API for ClandService service.
// All implementations must embed UnimplementedClandServiceServer
// for forward compatibility.
//
// ====================================================================
// ClandService: clapi → cland（控制面内部通信）
// 替代当前 cland 的 3 个 HTTP 端点
// ====================================================================
type ClandServiceServer interface {
	// 替代 POST /internal/execute
	Execute(context.Context, *ExecuteRequest) (*ExecuteReply, error)
	// 替代 POST /internal/node/add
	NodeAdd(context.Context, *NodeAddRequest) (*NodeAddReply, error)
	// 替代 POST /internal/node/remove
	NodeRemove(context.Context, *NodeRemoveRequest) (*NodeRemoveReply, error)
	// 文件传输（控制面 → 计算节点）
	TransmitFile(grpc.ClientStreamingServer[FileChunk, TransmitAck]) error
	// 分组管理
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsReply, error)
	mustEmbedUnimplementedClandServiceServer()
}

// UnimplementedClandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClandServiceServer struct{}

func (UnimplementedClandServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedClandServiceServer) NodeAdd(context.Context, *NodeAddRequest) (*NodeAddReply, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeAdd not implemented")
}
func (UnimplementedClandServiceServer) NodeRemove(context.Context, *NodeRemoveRequest) (*NodeRemoveReply, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeRemove not implemented")
}
func (UnimplementedClandServiceServer) TransmitFile(grpc.ClientStreamingServer[FileChunk, TransmitAck]) error {
	return status.Error(codes.Unimplemented, "method TransmitFile not implemented")
}
func (UnimplementedClandServiceServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedClandServiceServer) mustEmbedUnimplementedClandServiceServer() {}
func (UnimplementedClandServiceServer) testEmbeddedByValue()                      {}

// UnsafeClandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClandServiceServer will
// result in compilation errors.
type UnsafeClandServiceServer interface {
	mustEmbedUnimplementedClandServiceServer()
}

func RegisterClandServiceServer(s grpc.ServiceRegistrar, srv ClandServiceServer) {
	// If the following call panics, it indicates UnimplementedClandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClandService_ServiceDesc, srv)
}

func _ClandService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClandServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClandService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClandServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClandService_NodeAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClandServiceServer).NodeAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClandService_NodeAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClandServiceServer).NodeAdd(ctx, req.(*NodeAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClandService_NodeRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClandServiceServer).NodeRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClandService_NodeRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClandServiceServer).NodeRemove(ctx, req.(*NodeRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClandService_TransmitFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClandServiceServer).TransmitFile(&grpc.GenericServerStream[FileChunk, TransmitAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClandService_TransmitFileServer = grpc.ClientStreamingServer[FileChunk, TransmitAck]

func _ClandService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClandServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClandService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClandServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClandService_ServiceDesc is the grpc.ServiceDesc for ClandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudland.v1.ClandService",
	HandlerType: (*ClandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _ClandService_Execute_Handler,
		},
		{
			MethodName: "NodeAdd",
			Handler:    _ClandService_NodeAdd_Handler,
		},
		{
			MethodName: "NodeRemove",
			Handler:    _ClandService_NodeRemove_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _ClandService_ListGroups_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransmitFile",
			Handler:       _ClandService_TransmitFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "cloudland/v1/cloudland.proto",
}

const (
	CloudletService_CommandStream_FullMethodName = "/cloudland.v1.CloudletService/CommandStream"
	CloudletService_ReportHealth_FullMethodName  = "/cloudland.v1.CloudletService/ReportHealth"
)

// CloudletServiceClient is the client API for CloudletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ====================================================================
// CloudletService: cloudlet → cland（agent 注册 + 命令流）
// 替代整个 SCI 协议 + scidv1 握手
// ====================================================================
type CloudletServiceClient interface {
	// 双向 stream：cland 下发命令，cloudlet 回传结果
	CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CloudletMessage, ClandMessage], error)
	// 健康上报（独立 RPC，不占用命令 stream）
	ReportHealth(ctx context.Context, in *HealthReport, opts ...grpc.CallOption) (*HealthReportAck, error)
}

type cloudletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudletServiceClient(cc grpc.ClientConnInterface) CloudletServiceClient {
	return &cloudletServiceClient{cc}
}

func (c *cloudletServiceClient) CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CloudletMessage, ClandMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CloudletService_ServiceDesc.Streams[0], CloudletService_CommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CloudletMessage, ClandMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudletService_CommandStreamClient = grpc.BidiStreamingClient[CloudletMessage, ClandMessage]

func (c *cloudletServiceClient) ReportHealth(ctx context.Context, in *HealthReport, opts ...grpc.CallOption) (*HealthReportAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReportAck)
	err := c.cc.Invoke(ctx, CloudletService_ReportHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudletServiceServer is the server API for CloudletService service.
// All implementations must embed UnimplementedCloudletServiceServer
// for forward compatibility.
//
// ====================================================================
// CloudletService: cloudlet → cland（agent 注册 + 命令流）
// 替代整个 SCI 协议 + scidv1 握手
// ====================================================================
type CloudletServiceServer interface {
	// 双向 stream：cland 下发命令，cloudlet 回传结果
	CommandStream(grpc.BidiStreamingServer[CloudletMessage, ClandMessage]) error
	// 健康上报（独立 RPC，不占用命令 stream）
	ReportHealth(context.Context, *HealthReport) (*HealthReportAck, error)
	mustEmbedUnimplementedCloudletServiceServer()
}

// UnimplementedCloudletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudletServiceServer struct{}

func (UnimplementedCloudletServiceServer) CommandStream(grpc.BidiStreamingServer[CloudletMessage, ClandMessage]) error {
	return status.Error(codes.Unimplemented, "method CommandStream not implemented")
}
func (UnimplementedCloudletServiceServer) ReportHealth(context.Context, *HealthReport) (*HealthReportAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHealth not implemented")
}
func (UnimplementedCloudletServiceServer) mustEmbedUnimplementedCloudletServiceServer() {}
func (UnimplementedCloudletServiceServer) testEmbeddedByValue()                         {}

// UnsafeCloudletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudletServiceServer will
// result in compilation errors.
type UnsafeCloudletServiceServer interface {
	mustEmbedUnimplementedCloudletServiceServer()
}

func RegisterCloudletServiceServer(s grpc.ServiceRegistrar, srv CloudletServiceServer) {
	// If the following call panics, it indicates UnimplementedCloudletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudletService_ServiceDesc, srv)
}

func _CloudletService_CommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CloudletServiceServer).CommandStream(&grpc.GenericServerStream[CloudletMessage, ClandMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudletService_CommandStreamServer = grpc.BidiStreamingServer[CloudletMessage, ClandMessage]

func _CloudletService_ReportHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudletServiceServer).ReportHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudletService_ReportHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudletServiceServer).ReportHealth(ctx, req.(*HealthReport))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudletService_ServiceDesc is the grpc.ServiceDesc for CloudletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudland.v1.CloudletService",
	HandlerType: (*CloudletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportHealth",
			Handler:    _CloudletService_ReportHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommandStream",
			Handler:       _CloudletService_CommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cloudland/v1/cloudland.proto",
}
