/*
Copyright <holder> All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package services

// CloudLand pools on GPFS clusters (shared-storage-design.md §7.4): every pool is an independent fileset of a file
// system, linked at /gpfs/<fs>/<fileset>, which is the root of the pool on every member. The placement rules of a
// file system with two GPFS storage pools are generated by CloudLand as a whole.

import (
	"context"
	"encoding/json"
	"fmt"
	"path"
	"strings"
	"time"

	"api/src/model"

	"gorm.io/gorm"
)

const (
	gpfsDefaultInodeLimit = 100000
	gpfsPoolSystem        = "system"
	gpfsPoolData          = "data"
)

func (gpfsBackend) Capabilities() *StorageCapabilities {
	return &StorageCapabilities{Managed: true, External: true, Filesystems: true, Pools: true, AddNodes: true, RemoveNode: true, AddDisks: true,
		RemoveDisk: true, Rebalance: true, ReplaceDisk: true, ChangeRoles: true}
}

func (gpfsBackend) PoolDriver() string { return model.StorageDriverGPFS }

// gpfsPoolParams are the parameters of a pool on a GPFS cluster
type gpfsPoolParams struct {
	// Name of the file system; the first one of the cluster when empty
	Filesystem string `json:"filesystem,omitempty"`
	// Inodes of the fileset; volumes are few big files, the default is plenty
	InodeLimit int `json:"inode_limit,omitempty"`
}

// gpfsExternalPoolParams are the parameters of a pool on an imported cluster: a directory of its file system that
// its admins made (an independent fileset junction, typically), shown as is
type gpfsExternalPoolParams struct {
	Filesystem string `json:"filesystem,omitempty"`
	Path       string `json:"path"`
	Fileset    string `json:"fileset,omitempty"`
}

func (b gpfsBackend) externalPoolSetup(tx *gorm.DB, cluster *model.StorageCluster, pool *model.StoragePool, raw json.RawMessage) error {
	p := &gpfsExternalPoolParams{}
	if err := decodeStorageParams(b.Kind(), raw, p); err != nil {
		return err
	}
	fs := &model.StorageFilesystem{}
	q := tx.Where("cluster_id = ?", cluster.ID)
	if p.Filesystem != "" {
		q = q.Where("name = ?", p.Filesystem)
	}
	if err := q.Order("id").Take(fs).Error; err != nil {
		return planError("Storage cluster %s has no file system %s", cluster.Name, p.Filesystem)
	}
	if path.Clean(p.Path) != p.Path || !strings.HasPrefix(p.Path, fs.MountPoint+"/") || len(p.Path) > 200 ||
		strings.ContainsAny(p.Path, " '\"\\$`") {
		return planError("The pool directory must be a plain path under %s, the mount point of %s", fs.MountPoint, fs.Name)
	}
	var taken int64
	tx.Model(&model.StoragePool{}).Where("mount_path = ? AND id <> ?", p.Path, pool.ID).Count(&taken)
	if taken > 0 {
		return planError("Another pool uses %s already", p.Path)
	}
	params, _ := json.Marshal(map[string]interface{}{"fs_name": fs.Name, "fileset": p.Fileset, "external": true})
	pool.FilesystemID = fs.ID
	pool.DriverParams = string(params)
	pool.MountPath = p.Path
	pool.CloneMode = "copy"
	return nil
}

// gpfsFsPools tells the media of the GPFS storage pools of a file system, from the NSDs in it
func gpfsFsPools(tx *gorm.DB, fs *model.StorageFilesystem) (map[string]map[string]bool, error) {
	disks := []*model.StorageClusterDisk{}
	if err := tx.Where("cluster_id = ? AND fs_id = ?", fs.ClusterID, fs.ID).Find(&disks).Error; err != nil {
		return nil, err
	}
	pools := map[string]map[string]bool{}
	for _, d := range disks {
		p := diskAttr(d, "gpfs_pool")
		if p == "" {
			p = gpfsPoolSystem
		}
		if pools[p] == nil {
			pools[p] = map[string]bool{}
		}
		pools[p][d.Media] = true
	}
	return pools, nil
}

// PoolSetup: the file system of the pool, the GPFS storage pool its data goes to (by the media asked for), the
// fileset name made from the pool uuid and its junction. On an imported cluster: the directory that becomes the pool
func (b gpfsBackend) PoolSetup(tx *gorm.DB, cluster *model.StorageCluster, pool *model.StoragePool, raw json.RawMessage) error {
	if cluster.Mode == model.StorageModeExternal {
		return b.externalPoolSetup(tx, cluster, pool, raw)
	}
	p := &gpfsPoolParams{}
	if err := decodeStorageParams(b.Kind(), raw, p); err != nil {
		return err
	}
	if err := storageParamRange(b.Kind(), "inode_limit", p.InodeLimit, 1000, 100000000); err != nil {
		return err
	}
	if p.InodeLimit == 0 {
		p.InodeLimit = gpfsDefaultInodeLimit
	}
	fs := &model.StorageFilesystem{}
	q := tx.Where("cluster_id = ? AND status = ?", cluster.ID, "ready")
	if p.Filesystem != "" {
		q = q.Where("name = ?", p.Filesystem)
	}
	if err := q.Order("id").Take(fs).Error; err != nil {
		if p.Filesystem != "" {
			return planError("Storage cluster %s has no ready file system %s", cluster.Name, p.Filesystem)
		}
		return planError("Storage cluster %s has no ready file system", cluster.Name)
	}
	fsPools, err := gpfsFsPools(tx, fs)
	if err != nil {
		return err
	}
	gp := gpfsPoolSystem
	if pool.Media != "" {
		switch {
		case fsPools[gpfsPoolData][pool.Media]:
			gp = gpfsPoolData
		case fsPools[gpfsPoolSystem][pool.Media]:
			gp = gpfsPoolSystem
		default:
			return planError("File system %s has no %s disks", fs.Name, pool.Media)
		}
	}
	fileset := "cl_" + pool.UUID[:8]
	params, _ := json.Marshal(map[string]interface{}{"fs_name": fs.Name, "fileset": fileset, "gpfs_pool": gp, "inode_limit": p.InodeLimit})
	pool.FilesystemID = fs.ID
	pool.DriverParams = string(params)
	pool.MountPath = fs.MountPoint + "/" + fileset
	pool.CloneMode = "clone"
	return nil
}

// gpfsPoolTaskPlan lays out the pool tasks: the admin host changes the file system, then every member gets the list
// of pools (and probes a new one at once). A removal takes the pool out of the lists first, so no host probes it
// while its fileset goes away
func gpfsPoolTaskPlan(task string, cluster *model.StorageCluster, all, admins []int32) ([]*StorageStepPlan, error) {
	step := func(name, scope string, hosts []int32, timeout time.Duration) *StorageStepPlan {
		return &StorageStepPlan{Name: name, Scope: scope, Hostids: hosts, Timeout: timeout}
	}
	n, a := model.StorageStepScopeNodes, model.StorageStepScopeAdmin
	if cluster.Mode == model.StorageModeExternal {
		// The directory of the pool exists: it is registered (subdirectories and marker), never made or deleted
		switch task {
		case StorageTaskCreatePool:
			return []*StorageStepPlan{step("register_pool", a, admins, 10*time.Minute), step("sync_pools", n, all, 5*time.Minute)}, nil
		case StorageTaskDeletePool:
			return []*StorageStepPlan{step("sync_pools", n, all, 5*time.Minute), step("unregister_pool", a, admins, 10*time.Minute)}, nil
		}
		return nil, planError("A pool of an imported cluster has no %s", task)
	}
	switch task {
	case StorageTaskCreatePool:
		return []*StorageStepPlan{step("create_pool", a, admins, 15*time.Minute), step("sync_pools", n, all, 5*time.Minute)}, nil
	case StorageTaskUpdatePool:
		return []*StorageStepPlan{step("update_pool", a, admins, 10*time.Minute)}, nil
	case StorageTaskDeletePool:
		return []*StorageStepPlan{step("sync_pools", n, all, 5*time.Minute), step("delete_pool", a, admins, 30*time.Minute)}, nil
	}
	return nil, planError("GPFS clusters have no task %s", task)
}

func init() {
	registerSharedPoolTasks(model.StorageKindGPFS, map[string]map[string]*storageStepDef{
		StorageTaskCreatePool: {
			"create_pool":   {Script: "gpfs_pool.sh", Input: gpfsPoolInput("create"), Done: gpfsPolicyDone},
			"register_pool": {Script: "gpfs_pool.sh", Input: gpfsPoolInput("register")},
		},
		StorageTaskUpdatePool: {"update_pool": {Script: "gpfs_pool.sh", Input: gpfsPoolInput("quota")}},
		StorageTaskDeletePool: {
			"delete_pool":     {Script: "gpfs_pool.sh", Input: gpfsPoolInput("delete"), Done: gpfsPolicyDone},
			"unregister_pool": {Script: "gpfs_pool.sh", Input: gpfsPoolInput("unregister")},
		},
	})
}

// gpfsPolicyRule places the data of one fileset
type gpfsPolicyRule struct {
	Fileset  string `json:"fileset"`
	GpfsPool string `json:"gpfs_pool"`
}

// gpfsPolicy is the placement of a file system as CloudLand generates it: a rule per pool that still exists, and
// the default. Only a file system with a data pool needs one (§7.3)
func gpfsPolicy(tx *gorm.DB, fs *model.StorageFilesystem, without int64) (rules []gpfsPolicyRule, multi bool, err error) {
	fsPools, err := gpfsFsPools(tx, fs)
	if err != nil {
		return nil, false, err
	}
	multi = len(fsPools[gpfsPoolData]) > 0
	pools := []*model.StoragePool{}
	if err = tx.Where("filesystem_id = ? AND driver = ? AND id <> ? AND status <> ?", fs.ID, model.StorageDriverGPFS, without, model.StoragePoolDeleting).
		Order("id").Find(&pools).Error; err != nil {
		return
	}
	rules = []gpfsPolicyRule{}
	for _, p := range pools {
		dp := poolDriverParams(p)
		rules = append(rules, gpfsPolicyRule{Fileset: stringParam(dp, "fileset"), GpfsPool: stringParam(dp, "gpfs_pool")})
	}
	return
}

func gpfsPoolInput(action string) storageStepInput {
	return func(ctx context.Context, db *gorm.DB, task *model.StorageTask, step *model.StorageTaskStep, hostid int32) (interface{}, error) {
		cluster, _, _, err := storageClusterOfTask(db, task)
		if err != nil {
			return nil, err
		}
		pool, args, err := sharedPoolOfTask(db, task)
		if err != nil {
			return nil, err
		}
		fs := &model.StorageFilesystem{}
		if err := db.Take(fs, pool.FilesystemID).Error; err != nil {
			return nil, fmt.Errorf("the file system of pool %s is gone", pool.Name)
		}
		dp := poolDriverParams(pool)
		in := map[string]interface{}{"action": action, "cluster_uuid": cluster.UUID, "pool_uuid": pool.UUID, "fs_name": fs.Name,
			"fileset": stringParam(dp, "fileset"), "junction": pool.MountPath, "mount_point": fs.MountPoint}
		switch action {
		case "create":
			rules, multi, err := gpfsPolicy(db, fs, 0)
			if err != nil {
				return nil, err
			}
			in["inode_limit"] = dp["inode_limit"]
			in["quota_bytes"] = pool.QuotaBytes
			in["rules"], in["multi_pool"] = rules, multi
		case "quota":
			in["quota_bytes"] = args.QuotaBytes
		case "delete":
			rules, multi, err := gpfsPolicy(db, fs, pool.ID)
			if err != nil {
				return nil, err
			}
			in["rules"], in["multi_pool"] = rules, multi
		case "unregister":
			// The directory stays with its owners: the copies of images CloudLand made in it go (§9.6)
			if in["bases"], err = poolImageBases(db, pool); err != nil {
				return nil, err
			}
		}
		return in, nil
	}
}

// gpfsPolicyDone counts the placement rules the step installed on the file system
func gpfsPolicyDone(ctx context.Context, tx *gorm.DB, task *model.StorageTask, step *model.StorageTaskStep, runs []*model.StorageTaskRun) error {
	pool, _, err := sharedPoolOfTask(tx, task)
	if err != nil {
		return err
	}
	for _, r := range runs {
		res := struct {
			PolicyInstalled bool `json:"policy_installed"`
		}{}
		if json.Unmarshal([]byte(r.Result), &res) == nil && res.PolicyInstalled {
			return tx.Model(&model.StorageFilesystem{}).Where("id = ?", pool.FilesystemID).Update("policy_gen", gorm.Expr("policy_gen + 1")).Error
		}
	}
	return nil
}
