import client from './client'

// VPN gateway API. The shapes mirror the Go structs in api/src/apis/vpn.go
// (VpnGatewayResponse, VpnConnectionResponse, VpnClientResponse and their payloads).

export type VpnGatewayStatus = 'pending' | 'available' | 'error' | 'deleting'
export type VpnConnectionStatus = 'pending' | 'down' | 'up' | 'error'
export type VpnRouteMode = 'static' | 'bgp'
export type VpnDpdAction = 'restart' | 'clear' | 'none'

// One of the two HA nodes of a gateway (the VRRP master / backup pair)
export interface VpnNodeInfo {
    hostid: number
    hostname: string
    role: 'MASTER' | 'BACKUP' | string
    // True for the node currently holding the public address
    master: boolean
}

// A remote network routed through the gateway; source tells where it came from (static connection, BGP, client pool)
export interface VpnPrefix {
    cidr: string
    source: string
    ref_id: number
}

// BGP snapshot reported by the master node for a BGP-routed connection (display only).
// The lists are Go slices and come back as null when empty.
export interface VpnBgpReport {
    name: string
    state: string
    uptime: string
    prefixes_received: number
    prefixes_sent: number
    // Prefixes the peer advertised inside remote_summary_cidrs
    accepted: string[] | null
    // Prefixes the peer advertised outside remote_summary_cidrs: the summary networks are too narrow
    rejected: string[] | null
    // Local networks actually advertised to the peer (a subnet without an instance is not advertised)
    advertised: string[] | null
    truncated: boolean
}

export interface VpnConnection {
    id: string
    name: string
    description?: string
    owner?: string
    owner_uuid?: string
    created_at?: string
    updated_at?: string
    status: VpnConnectionStatus | string
    // Empty when the gateway only responds to the peer
    remote_gateway: string
    remote_id: string
    local_id: string
    route_mode: VpnRouteMode | string
    // Comma separated; empty means all VPC internal subnets (see effective_local_cidrs)
    local_cidrs: string
    effective_local_cidrs: string[] | null
    remote_cidrs: string
    remote_summary_cidrs: string
    max_prefixes: number
    local_asn: number
    peer_asn: number
    tunnel_local_ip: string
    tunnel_peer_ip: string
    bgp_password_set: boolean
    bgp_keepalive: number
    bgp_hold: number
    auth_method: string
    psk_set: boolean
    ike_version: number
    ike_proposal: string
    esp_proposal: string
    ike_lifetime: number
    esp_lifetime: number
    dpd_action: VpnDpdAction | string
    dpd_delay: number
    initiator: boolean
    if_id: number
    established_at?: string
    bytes_in: number
    bytes_out: number
    last_error: string
    bgp?: VpnBgpReport | null
    bgp_reported_at?: string
}

export interface VpnClient {
    id: string
    name: string
    description?: string
    created_at?: string
    updated_at?: string
    protocol: string
    ip_address: string
    public_key: string
    preshared_key_set: boolean
    enabled: boolean
    last_handshake_at?: string
    bytes_in: number
    bytes_out: number
}

// Returned by the create call only: the private key (when generated by the platform) is never stored
export interface VpnClientCreateResponse extends VpnClient {
    private_key?: string
    config: string
}

export interface VpnGateway {
    id: string
    name: string
    description?: string
    owner?: string
    owner_uuid?: string
    created_at?: string
    updated_at?: string
    status: VpnGatewayStatus | string
    vpc?: { id: string; name: string }
    zone?: string
    floating_ips?: Array<{ id: string; name?: string; fip_address?: string }>
    public_ip: string
    /** false: the gateway is paused (tunnels, BGP and WireGuard stopped, public IP kept) */
    enabled: boolean
    ipsec_enabled: boolean
    client_enabled: boolean
    client_protocol: string
    client_cidr: string
    client_port: number
    client_public_key: string
    client_dns: string
    // Comma separated; empty means all VPC internal subnets (see effective_client_routes)
    client_routes: string
    effective_client_routes: string[] | null
    master_hyper: number
    master_hostname: string
    master_reported_at?: string
    nodes: VpnNodeInfo[] | null
    connection_count: number
    client_count: number
    // Detail only (omitted by the list call)
    connections?: VpnConnection[]
    clients?: VpnClient[]
    remote_prefixes?: VpnPrefix[]
}

export interface VpnGatewayListResponse {
    offset: number
    total: number
    limit: number
    vpn_gateways: VpnGateway[]
}

export interface VpnGatewayPayload {
    name: string
    description?: string
    vpc: { id: string }
    zone?: string
    public_subnet?: { id: string }
    public_ip?: string
    inbound?: number
    outbound?: number
    ipsec_enabled?: boolean
    client_enabled?: boolean
    client_cidr?: string
    client_port?: number
    client_dns?: string
    client_routes?: string
}

export interface VpnGatewayPatchPayload {
    name?: string
    description?: string
    enabled?: boolean
    ipsec_enabled?: boolean
    client_enabled?: boolean
    client_cidr?: string
    client_port?: number
    client_dns?: string
    client_routes?: string
}

// psk is required on create; psk and bgp_password are write-only
export interface VpnConnectionPayload {
    name: string
    description?: string
    remote_gateway?: string
    remote_id?: string
    local_id?: string
    route_mode?: VpnRouteMode
    local_cidrs?: string
    remote_cidrs?: string
    remote_summary_cidrs?: string
    max_prefixes?: number
    local_asn?: number
    peer_asn?: number
    tunnel_local_ip?: string
    tunnel_peer_ip?: string
    bgp_password?: string
    bgp_keepalive?: number
    bgp_hold?: number
    psk?: string
    ike_proposal?: string
    esp_proposal?: string
    ike_lifetime?: number
    esp_lifetime?: number
    dpd_action?: VpnDpdAction
    dpd_delay?: number
    initiator?: boolean
}

// Every field is optional on update; an omitted field keeps its stored value
export type VpnConnectionPatchPayload = Partial<VpnConnectionPayload>

export interface VpnClientPayload {
    name: string
    description?: string
    // Empty: the platform generates the key pair and returns the private key once
    public_key?: string
    preshared_key?: boolean
    enabled?: boolean
}

export interface VpnClientPatchPayload {
    name?: string
    description?: string
    enabled?: boolean
}

export interface VpnClientConfigResponse {
    // WireGuard config without the private key (placeholder <your private key>)
    config: string
}

export const vpnGatewaysApi = {
    list: async (params?: {
        offset?: number
        limit?: number
        order?: string
        query?: string
        vpc_id?: string
    }): Promise<VpnGatewayListResponse> => {
        const response = await client.get('/vpn_gateways', { params })
        return response.data
    },
    get: async (id: string): Promise<VpnGateway> => {
        const response = await client.get(`/vpn_gateways/${id}`)
        return response.data
    },
    create: async (payload: VpnGatewayPayload): Promise<VpnGateway> => {
        const response = await client.post('/vpn_gateways', payload)
        return response.data
    },
    update: async (id: string, payload: VpnGatewayPatchPayload): Promise<VpnGateway> => {
        const response = await client.patch(`/vpn_gateways/${id}`, payload)
        return response.data
    },
    delete: async (id: string): Promise<void> => {
        await client.delete(`/vpn_gateways/${id}`)
    },
}

export const vpnConnectionsApi = {
    list: async (gatewayId: string): Promise<{ total: number; connections: VpnConnection[] }> => {
        const response = await client.get(`/vpn_gateways/${gatewayId}/connections`)
        return response.data
    },
    get: async (gatewayId: string, connId: string): Promise<VpnConnection> => {
        const response = await client.get(`/vpn_gateways/${gatewayId}/connections/${connId}`)
        return response.data
    },
    create: async (gatewayId: string, payload: VpnConnectionPayload): Promise<VpnConnection> => {
        const response = await client.post(`/vpn_gateways/${gatewayId}/connections`, payload)
        return response.data
    },
    update: async (gatewayId: string, connId: string, payload: VpnConnectionPatchPayload): Promise<VpnConnection> => {
        const response = await client.patch(`/vpn_gateways/${gatewayId}/connections/${connId}`, payload)
        return response.data
    },
    delete: async (gatewayId: string, connId: string): Promise<void> => {
        await client.delete(`/vpn_gateways/${gatewayId}/connections/${connId}`)
    },
    // Terminates and re-initiates the IKE SA
    restart: async (gatewayId: string, connId: string): Promise<VpnConnection> => {
        const response = await client.post(`/vpn_gateways/${gatewayId}/connections/${connId}/restart`)
        return response.data
    },
}

export const vpnClientsApi = {
    list: async (gatewayId: string): Promise<{ total: number; clients: VpnClient[] }> => {
        const response = await client.get(`/vpn_gateways/${gatewayId}/clients`)
        return response.data
    },
    get: async (gatewayId: string, clientId: string): Promise<VpnClient> => {
        const response = await client.get(`/vpn_gateways/${gatewayId}/clients/${clientId}`)
        return response.data
    },
    create: async (gatewayId: string, payload: VpnClientPayload): Promise<VpnClientCreateResponse> => {
        const response = await client.post(`/vpn_gateways/${gatewayId}/clients`, payload)
        return response.data
    },
    update: async (gatewayId: string, clientId: string, payload: VpnClientPatchPayload): Promise<VpnClient> => {
        const response = await client.patch(`/vpn_gateways/${gatewayId}/clients/${clientId}`, payload)
        return response.data
    },
    delete: async (gatewayId: string, clientId: string): Promise<void> => {
        await client.delete(`/vpn_gateways/${gatewayId}/clients/${clientId}`)
    },
    // Config template without the private key, for a client whose key was generated earlier or brought by the user
    config: async (gatewayId: string, clientId: string): Promise<VpnClientConfigResponse> => {
        const response = await client.get(`/vpn_gateways/${gatewayId}/clients/${clientId}/config`)
        return response.data
    },
}

export default {
    gateways: vpnGatewaysApi,
    connections: vpnConnectionsApi,
    clients: vpnClientsApi,
}
