// Proxy route whitelist ported from the Python CPGateway routes (cpgateway/app/api/endpoints/cloudland/*.py, since removed).

package apis

type proxyRoute struct {
	Method   string
	Path     string // gin route under /api/v1
	Template string // backend path; {name} is replaced by the route param
	Admin    bool   // requires SystemAdmin
}

var proxyRoutes = []proxyRoute{
	// compute.py
	{"GET", "/backups", "/backups", false},
	{"POST", "/backups", "/backups", false},
	{"GET", "/backups/:id", "/backups/{id}", false},
	{"DELETE", "/backups/:id", "/backups/{id}", false},
	{"POST", "/backups/:id/restore", "/backups/{id}/restore", false},
	{"GET", "/dictionaries", "/dictionaries", false},
	{"POST", "/dictionaries", "/dictionaries", false},
	{"GET", "/dictionaries/:id", "/dictionaries/{id}", false},
	{"DELETE", "/dictionaries/:id", "/dictionaries/{id}", false},
	{"PATCH", "/dictionaries/:id", "/dictionaries/{id}", false},
	{"GET", "/flavors", "/flavors", false},
	{"POST", "/flavors", "/flavors", false},
	{"GET", "/flavors/:name", "/flavors/{name}", false},
	{"DELETE", "/flavors/:name", "/flavors/{name}", false},
	{"GET", "/images", "/images", false},
	{"POST", "/images", "/images", false},
	{"GET", "/images/:id", "/images/{id}", false},
	{"DELETE", "/images/:id", "/images/{id}", false},
	{"PATCH", "/images/:id", "/images/{id}", false},
	{"GET", "/images/:id/storages", "/images/{id}/storages", false},
	{"GET", "/instances", "/instances", false},
	{"POST", "/instances", "/instances", false},
	{"GET", "/instances/rule-links", "/instances/rule-links", false},
	{"GET", "/instances/:id", "/instances/{id}", false},
	{"DELETE", "/instances/:id", "/instances/{id}", false},
	{"PATCH", "/instances/:id", "/instances/{id}", false},
	{"POST", "/instances/:id/console", "/instances/{id}/console", false},
	{"POST", "/instances/:id/end_rescue", "/instances/{id}/end_rescue", false},
	{"POST", "/instances/:id/reinstall", "/instances/{id}/reinstall", false},
	{"POST", "/instances/:id/rescue", "/instances/{id}/rescue", false},
	{"POST", "/instances/:id/resize", "/instances/{id}/resize", false},
	{"POST", "/instances/:id/set_user_password", "/instances/{id}/set_user_password", false},
	{"GET", "/migrations", "/migrations", false},
	{"POST", "/migrations", "/migrations", false},
	{"GET", "/migrations/:id", "/migrations/{id}", false},
	{"GET", "/tasks", "/tasks", false},
	{"GET", "/tasks/:id", "/tasks/{id}", false},
	{"GET", "/version", "/version", false},
	{"GET", "/volumes", "/volumes", false},
	{"POST", "/volumes", "/volumes", false},
	{"GET", "/volumes/:id", "/volumes/{id}", false},
	{"DELETE", "/volumes/:id", "/volumes/{id}", false},
	{"PATCH", "/volumes/:id", "/volumes/{id}", false},
	{"PUT", "/volumes/:id/qos", "/volumes/{id}/qos", false},
	{"POST", "/volumes/:id/resize", "/volumes/{id}/resize", false},
	// network.py
	{"GET", "/floating_ips", "/floating_ips", false},
	{"POST", "/floating_ips", "/floating_ips", false},
	{"POST", "/floating_ips/batch_attach", "/floating_ips/batch_attach", false},
	{"POST", "/floating_ips/batch_detach", "/floating_ips/batch_detach", false},
	{"GET", "/floating_ips/:id", "/floating_ips/{id}", false},
	{"DELETE", "/floating_ips/:id", "/floating_ips/{id}", false},
	{"PATCH", "/floating_ips/:id", "/floating_ips/{id}", false},
	{"GET", "/instances/:id/interfaces", "/instances/{id}/interfaces", false},
	{"POST", "/instances/:id/interfaces", "/instances/{id}/interfaces", false},
	{"DELETE", "/instances/:id/interfaces/:interface_id", "/instances/{id}/interfaces/{interface_id}", false},
	{"GET", "/instances/:id/interfaces/:interface_id", "/instances/{id}/interfaces/{interface_id}", false},
	{"PATCH", "/instances/:id/interfaces/:interface_id", "/instances/{id}/interfaces/{interface_id}", false},
	{"GET", "/ip_groups", "/ip_groups", false},
	{"POST", "/ip_groups", "/ip_groups", false},
	{"GET", "/ip_groups/:id", "/ip_groups/{id}", false},
	{"DELETE", "/ip_groups/:id", "/ip_groups/{id}", false},
	{"PATCH", "/ip_groups/:id", "/ip_groups/{id}", false},
	{"GET", "/load_balancers", "/load_balancers", false},
	{"POST", "/load_balancers", "/load_balancers", false},
	{"GET", "/load_balancers/:id", "/load_balancers/{id}", false},
	{"DELETE", "/load_balancers/:id", "/load_balancers/{id}", false},
	{"PATCH", "/load_balancers/:id", "/load_balancers/{id}", false},
	{"GET", "/load_balancers/:id/floating_ips", "/load_balancers/{id}/floating_ips", false},
	{"POST", "/load_balancers/:id/floating_ips", "/load_balancers/{id}/floating_ips", false},
	{"GET", "/load_balancers/:id/floating_ips/:floating_ip_id", "/load_balancers/{id}/floating_ips/{floating_ip_id}", false},
	{"DELETE", "/load_balancers/:id/floating_ips/:floating_ip_id", "/load_balancers/{id}/floating_ips/{floating_ip_id}", false},
	{"GET", "/load_balancers/:id/listeners", "/load_balancers/{id}/listeners", false},
	{"POST", "/load_balancers/:id/listeners", "/load_balancers/{id}/listeners", false},
	{"GET", "/load_balancers/:id/listeners/:listener_id/backends", "/load_balancers/{id}/listeners/{listener_id}/backends", false},
	{"DELETE", "/load_balancers/:id/listeners/:listener_id/backends/:backend_id", "/load_balancers/{id}/listeners/{listener_id}/backends/{backend_id}", false},
	{"GET", "/load_balancers/:id/listeners/:listener_id", "/load_balancers/{id}/listeners/{listener_id}", false},
	{"DELETE", "/load_balancers/:id/listeners/:listener_id", "/load_balancers/{id}/listeners/{listener_id}", false},
	{"PATCH", "/load_balancers/:id/listeners/:listener_id", "/load_balancers/{id}/listeners/{listener_id}", false},
	{"POST", "/load_balancers/:id/listeners/:listener_id/backends", "/load_balancers/{id}/listeners/{listener_id}/backends", false},
	{"GET", "/load_balancers/:id/listeners/:listener_id/backends/:backend_id", "/load_balancers/{id}/listeners/{listener_id}/backends/{backend_id}", false},
	{"PATCH", "/load_balancers/:id/listeners/:listener_id/backends/:backend_id", "/load_balancers/{id}/listeners/{listener_id}/backends/{backend_id}", false},
	{"GET", "/security_groups", "/security_groups", false},
	{"POST", "/security_groups", "/security_groups", false},
	{"GET", "/security_groups/:id", "/security_groups/{id}", false},
	{"DELETE", "/security_groups/:id", "/security_groups/{id}", false},
	{"PATCH", "/security_groups/:id", "/security_groups/{id}", false},
	{"GET", "/security_groups/:id/rules", "/security_groups/{id}/rules", false},
	{"POST", "/security_groups/:id/rules", "/security_groups/{id}/rules", false},
	{"GET", "/security_groups/:id/rules/:rule_id", "/security_groups/{id}/rules/{rule_id}", false},
	{"DELETE", "/security_groups/:id/rules/:rule_id", "/security_groups/{id}/rules/{rule_id}", false},
	{"PATCH", "/security_groups/:id/rules/:rule_id", "/security_groups/{id}/rules/{rule_id}", false},
	{"GET", "/subnets", "/subnets", false},
	{"POST", "/subnets", "/subnets", false},
	{"GET", "/subnets/:id", "/subnets/{id}", false},
	{"DELETE", "/subnets/:id", "/subnets/{id}", false},
	{"PATCH", "/subnets/:id", "/subnets/{id}", false},
	{"GET", "/addresses/:uuid", "/addresses/{uuid}", false},
	{"PATCH", "/subnets/:id/addresses/:address_id", "/subnets/{id}/addresses/{address_id}", false},
	{"PATCH", "/subnets/:id/addresses/:address_id/update-lock", "/subnets/{id}/addresses/{address_id}/update-lock", false},
	{"GET", "/vpcs", "/vpcs", false},
	{"POST", "/vpcs", "/vpcs", false},
	{"GET", "/vpcs/:id", "/vpcs/{id}", false},
	{"DELETE", "/vpcs/:id", "/vpcs/{id}", false},
	{"PATCH", "/vpcs/:id", "/vpcs/{id}", false},
	// authorization.py
	{"GET", "/keys", "/keys", false},
	{"POST", "/keys", "/keys", false},
	{"GET", "/keys/:id", "/keys/{id}", false},
	{"DELETE", "/keys/:id", "/keys/{id}", false},
	{"PATCH", "/keys/:id", "/keys/{id}", false},
	// zone.py
	{"GET", "/zones", "/zones", false},
	{"POST", "/zones", "/zones", false},
	{"GET", "/zones/:name", "/zones/{name}", false},
	{"DELETE", "/zones/:name", "/zones/{name}", false},
	{"PATCH", "/zones/:name", "/zones/{name}", false},
	// administration.py
	// 审计日志：记录改动型操作的发起人与结果，仅系统管理员可查
	{"GET", "/audit_logs", "/audit_logs", true},
	// 组织操作动态：同一份审计数据的精简视图，范围由 clapi 限定为当前组织，所有成员可见
	{"GET", "/activities", "/activities", false},

	{"GET", "/hypers", "/hypers", true},
	{"GET", "/hypers/:hostid", "/hypers/{hostid}", true},
	{"PATCH", "/hypers/:hostid", "/hypers/{hostid}", true},
	{"POST", "/hypers", "/hypers", true},
	{"POST", "/hypers/:hostid/maintain", "/hypers/{hostid}/maintain", true},
	{"DELETE", "/hypers/:hostid", "/hypers/{hostid}", true},
	{"GET", "/node-alarm-rules", "/node-alarm-rules", true},
	{"POST", "/node-alarm-rules", "/node-alarm-rules", true},
	{"DELETE", "/node-alarm-rules/:uuid", "/node-alarm-rules/{uuid}", true},
	// alarm.py
	{"POST", "/metrics/alarm/sync-mappings", "/metrics/alarm/sync-mappings", false},
	{"GET", "/alarm/events", "/alarm/events", false},
	{"GET", "/alarm/events/:event_uuid/delivery-logs", "/alarm/events/{event_uuid}/delivery-logs", false},
	{"POST", "/alarm/rule-channels", "/alarm/rule-channels", false},
	{"GET", "/alarm/rule-channels/:rule_group_uuid", "/alarm/rule-channels/{rule_group_uuid}", false},
	{"POST", "/metrics/alarm/cpu/rules", "/metrics/alarm/cpu/rules", false},
	{"GET", "/metrics/alarm/cpu/rules", "/metrics/alarm/cpu/rules", false},
	{"DELETE", "/metrics/alarm/cpu/rule/:uuid", "/metrics/alarm/cpu/rule/{uuid}", false},
	{"POST", "/metrics/alarm/memory/rules", "/metrics/alarm/memory/rules", false},
	{"GET", "/metrics/alarm/memory/rules", "/metrics/alarm/memory/rules", false},
	{"DELETE", "/metrics/alarm/memory/rule/:uuid", "/metrics/alarm/memory/rule/{uuid}", false},
	{"POST", "/metrics/alarm/bw/rules", "/metrics/alarm/bw/rules", false},
	{"GET", "/metrics/alarm/bw/rules", "/metrics/alarm/bw/rules", false},
	{"DELETE", "/metrics/alarm/bw/rule/:uuid", "/metrics/alarm/bw/rule/{uuid}", false},
	{"GET", "/metrics/alarm/active-rules", "/metrics/alarm/active-rules", false},
	{"POST", "/metrics/alarm/:uuid/enable", "/metrics/alarm/{uuid}/enable", false},
	{"POST", "/metrics/alarm/:uuid/disable", "/metrics/alarm/{uuid}/disable", false},
	{"POST", "/metrics/alarm/link", "/metrics/alarm/link", false},
	{"POST", "/metrics/alarm/unlink", "/metrics/alarm/unlink", false},
	// monitor.py
	{"POST", "/metrics/instances/cpu/his_data", "/metrics/instances/cpu/his_data", false},
	{"POST", "/metrics/instances/memory/his_data", "/metrics/instances/memory/his_data", false},
	{"POST", "/metrics/instances/disk/his_data", "/metrics/instances/disk/his_data", false},
	{"POST", "/metrics/instances/network/his_data", "/metrics/instances/network/his_data", false},
	{"POST", "/metrics/instances/traffic/his_data", "/metrics/instances/traffic/his_data", false},
	{"POST", "/metrics/instances/volume/his_data", "/metrics/instances/volume/his_data", false},
	{"POST", "/metrics/hypers/cpu/his_data", "/metrics/hypers/cpu/his_data", false},
	{"POST", "/metrics/hypers/memory/his_data", "/metrics/hypers/memory/his_data", false},
}
